name: RDP with Guacamole Access

on:
  workflow_dispatch:

jobs:
  rdp-with-guacamole:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Enable RDP and create user
      run: |
        net user guacuser guacpass /add
        net localgroup administrators guacuser /add
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        echo ✅ RDP Enabled and User Created.

    - name: Install Docker Desktop
      run: |
        choco install docker-desktop --confirm
        echo ✅ Docker Installed

    - name: Start Docker service
      run: |
        Start-Process "C:\Program Files\Docker\Docker\Docker Desktop.exe"
        Start-Sleep -Seconds 30

    - name: Create docker-compose file
      shell: pwsh
      run: |
        echo 'version: "2"
        services:
          guacd:
            image: guacamole/guacd
            container_name: guacd
            restart: always
          guacamole:
            image: guacamole/guacamole
            container_name: guacamole
            restart: always
            ports:
              - "8080:8080"
            environment:
              GUACD_HOSTNAME: guacd
              GUACAMOLE_HOME: /guac-home
            volumes:
              - ./guac-home:/guac-home' | Out-File -Encoding utf8 docker-compose.yml

    - name: Setup Guacamole config
      shell: pwsh
      run: |
        mkdir guac-home
        mkdir guac-home\user-mapping
        $xml = @"
        <user-mapping>
          <authorize username="admin" password="admin">
            <connection name="Windows-RDP">
              <protocol>rdp</protocol>
              <param name="hostname">127.0.0.1</param>
              <param name="port">3389</param>
              <param name="username">guacuser</param>
              <param name="password">guacpass</param>
            </connection>
          </authorize>
        </user-mapping>
        "@
        $xml | Out-File -Encoding utf8 guac-home\user-mapping.xml

    - name: Start Guacamole containers
      run: docker-compose up -d

    - name: Tunnel using Serveo
      run: |
        ssh -o StrictHostKeyChecking=no -R 80:localhost:8080 serveo.net &
        timeout /t 15
        echo 🌐 Access from browser using Serveo public link on port 80
        echo 👤 Login: admin / admin

    - name: Keep session alive
      run: |
        while ($true) { Start-Sleep -Seconds 300 }
